spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_temp?createDatabaseIfNotExist=true
    username: root
    password: MyPassword

server:
  port: 8080

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,ETB,GBP,AB

payment-gateway: paypal
notification-service: email

mail-server:
  host: https://smtp.gmail.com
  port: 5761

# Model first approach with hibernate
jpa:
  hibernate:
  ddl-auto: create
